name: flutter_clean_app
description: A Flutter application demonstrating Clean Architecture.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core / Utils
  equatable: ^2.0.5
  get_it: ^7.6.4

  # State Management (Example: flutter_bloc - choose one or add later)
  # flutter_bloc: ^8.1.3
  # provider: ^6.0.5
  # riverpod: ^2.4.9

  # Data Layer (Examples - add specific ones later)
  # http: ^1.1.0
  # shared_preferences: ^2.2.2
  # sqflite: ^2.3.0
  # isar: ^3.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Code Generation (if using libraries like Isar, Freezed, etc.)
  # build_runner: ^2.4.6
  # isar_generator: ^3.1.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
